void setup() {
pinMode(3,OUTPUT);
pinMode(4,OUTPUT);
pinMode(5,OUTPUT);
pinMode(6,OUTPUT);
pinMode(7,OUTPUT);
pinMode(8,OUTPUT);
pinMode(9,OUTPUT);
}

void loop() {
digitalWrite(3,HIGH);
delay(50);
digitalWrite(3,LOW);
delay(50);
digitalWrite(3,HIGH);
delay(50);
digitalWrite(3,LOW);
delay(50);
digitalWrite(4,HIGH);
delay(50);
digitalWrite(4,LOW);
delay(50);
digitalWrite(4,HIGH);
delay(50);
digitalWrite(4,LOW);
delay(50);
digitalWrite(5,HIGH);
delay(50);
digitalWrite(5,LOW);
delay(50);
digitalWrite(5,HIGH);
delay(50);
digitalWrite(5,LOW);
delay(50);
digitalWrite(6,HIGH);
delay(50);
digitalWrite(6,LOW);
delay(50);
digitalWrite(6,HIGH);
delay(50);
digitalWrite(6,LOW);
delay(50);
digitalWrite(7,HIGH);
delay(50);
digitalWrite(7,LOW);
delay(50);
digitalWrite(7,HIGH);
delay(50);
digitalWrite(7,LOW);
delay(50);
digitalWrite(8,HIGH);
delay(50);
digitalWrite(8,LOW);
delay(50);
digitalWrite(8,HIGH);
delay(50);
digitalWrite(8,LOW);
delay(50);
digitalWrite(9,HIGH);
delay(50);
digitalWrite(9,LOW);
delay(50);
digitalWrite(9,HIGH);
delay(50);
digitalWrite(9,LOW);
delay(50);


}
